name: CI

on: push

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
      
      - name: Instalando as dependências
        run: npm install

      - name: Executando os testes unitários
        run: npm run test